### ISSUE TITLE
VSCode extension error: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by Real-Gecko** [mercari/grpc-federation#246]
**Describe the bug**

** Related Components **
- [ ] protoc-gen-grpc-federation
- [ ] grpc-federation-linter
- [ ] grpc-federation-language-server
- [ ] grpc-federation-generator
- [ ] others

**To Reproduce**
Start vscode and open protofile
Go to `extension host` in output tab
Observe the crash message 

**Expected behavior**
Expected extension to work

**Screenshots**
![image](https://github.com/user-attachments/assets/dc3b60ca-eb1d-40d8-86f3-b5ca6652e2dc)

**Additional context**
Extension is installed on remote machine. Yesterday everything worked as expected but today I get the error.
```log
2024-09-20 05:53:43.483 [error] Activating extension mercari.grpc-federation failed due to an error:
2024-09-20 05:53:43.483 [error] TypeError: Cannot read properties of undefined (reading 'map')
	at activate (/home/ubuntu/.vscode-server/extensions/mercari.grpc-federation-1.5.1/out/extension.js:18:34)
	at q.kb (/home/ubuntu/.vscode-server/cli/servers/Stable-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/server/out/vs/workbench/api/node/extensionHostProcess.js:167:13836)
	at q.jb (/home/ubuntu/.vscode-server/cli/servers/Stable-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/server/out/vs/workbench/api/node/extensionHostProcess.js:167:13508)
	at /home/ubuntu/.vscode-server/cli/servers/Stable-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/server/out/vs/workbench/api/node/extensionHostProcess.js:167:11493
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async m.n (/home/ubuntu/.vscode-server/cli/servers/Stable-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/server/out/vs/workbench/api/node/extensionHostProcess.js:151:6409)
	at async m (/home/ubuntu/.vscode-server/cli/servers/Stable-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/server/out/vs/workbench/api/node/extensionHostProcess.js:151:6372)
	at async m.l (/home/ubuntu/.vscode-server/cli/servers/Stable-38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/server/out/vs/workbench/api/node/extensionHostProcess.js:151:5829)
```

**Comment by Real-Gecko** [comment]
Still relevant with extension version 1.6.0

**Comment by Real-Gecko** [comment]
This happens in multiroot workspaces, I guess due to workspace folder being hardcoded
https://github.com/mercari/grpc-federation/blob/c188207ee810463e5ac50be9d85aac3ee4fcf712/lsp/client/vscode/src/extension.ts#L21
